
    sleep 20;
   player globalchat "[server] Welcome To HD | ChocoLand | Wasteland MOD BaseDefense!";
    player globalchat "[server] Visit www.heavensdelight.de ";
    player globalchat "[server] Please follow ALL rules or you'll have lots of fun.";
    player globalchat "[server] Server restart at 8 PM";
    sleep 60;
	player globalchat "[server] Player save is enabled on this server";
	player globalchat "[server] VOIP Is Disabled";
        player globalchat "[server] We hope you enjoy our game servers! filter Chocoland";
    sleep 120;
	player globalchat "[server] There are VIP packages available for donators on this server, for more info or to donate, visit our forums.";
	player globalchat "[server] Be one with ChocoLand";
        player globalchat "[server] We can be both of God and Devil, since we`re trying to raise the dead against the stream of Time";
    sleep 120;
        player globalchat "[server] Please advertises for us to keep these servers alive!, without advertising would suffer the game fun !";
        player globalchat "[server]  Is it true that vampires don't like clowns because their blood tastes funny?";
    sleep 120;
	player globalchat "[server] Become the best in the highscore and get the unique bonus";
	player globalchat "[server] can you tell me where I can find a gun here";
    sleep 120;
	player globalchat "[server] Have an idea? let us know what it is and maybe we can implement it on one of our servers!";
	player globalchat "[server] Do people staying at the poles see the world upside down?";
    sleep 120;
    	player globalchat "[server] What is the speed of darkness?";
    sleep 240;
